#ifndef REGIONSOFMAPS_H_INCLUDED
#define REGIONSOFMAPS_H_INCLUDED

enum class RegionsOfMaps {

    TWO_PLAYER_MAP__REGION_ONE,
    TWO_PLAYER_MAP__REGION_ONE,
    THREE_PLAYER_MAP__REGION_ONE,
    THREE_PLAYER_MAP__REGION_TWO,
    FOUR_PLAYER_MAP__REGION_ONE,
    FOUR_PLAYER_MAP__REGION_TWO,
    FIVE_PLAYER_MAP__REGION_ONE,
    FIVE_PLAYER_MAP__REGION_TWO
}

#endif // REGIONSOFMAPS_H_INCLUDED
