#ifndef REGIONPIECESHELPER_HPP_
#define REGIONPIECESHELPER_HPP_

enum class RegionPieces {
    TROLL_LAIR,
    FORTRESS,
    MOUNTAIN,
    ENCAMPMENT,
    HOLES_IN_GROUND,
    HERO,
    DRAGON,
	NO_REGION_PIECE
};

#endif /* REGIONPIECES_HPP_ */
