#ifndef USERINTERFACECODES_HPP_
#define USERINTERFACECODES_HPP_

enum class UserInterfaceCodes {

//	DISPLAY_CURRENT_SNAPSHOT,
//	PAUSE_GAME,
//	RESUME_GAME
	SELECTED_TO_DECLINE_ACTIVE_RACE
};

#endif /* USERINTERFACECODES_HPP_ */
